name: liconic_module
services:
  liconic_module:
    container_name: liconic_module
    image: ghcr.io/ad-sdl/liconic_module
    network_mode: host
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/liconic_module:latest
        - ghcr.io/ad-sdl/liconic_module:dev
    command: python -m liconic_rest_node
    # --port 2010 --device ${DEVICE} --resources_path ${RESOURCES_PATH}
    volumes:
      - ./definitions:/home/madsci/definitions/
